### ISSUE TITLE
infografia hilos

### ISSUE THREAD

**Issue by Luisangelriverosbautista** [SistemasTecTlaxiaco/infografia-de-hilos-Luisangelriverosbautista#2]
[infografias hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Luisangelriverosbautista/files/15098655/infografias.hilos.pdf)

**Comment by Kim-Mendoza3** [comment]
calificacion 19

**Comment by josealfredo79** [comment]
faltan las referencias

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
